GET http://localhost:3400/employee
###

GET http://localhost:3500/employee/1


###
POST http://localhost:3400/employee
Content-Type: application/json

{
    "firstname":"ismail",
    "lastname":"zaabi"

}
###

DELETE http://localhost:3400/employee/id:1
